kiosk_id: "fe7ef5cd7c273ec75600d6c710216f69"
anchor_product_id: "000056-002"
included_products: ""
excluded_products: "004747-001"
allowed_categories: ""
agg_key: ""
n_group_key: 2
n_min: 4
n_max: 10
predictions_path: training/data/interim/predictions.parquet
popularity_path: training/data/interim/popularity_fallback.parquet
products_path: training/data/external/products_v2.csv
