extends: base_train.yaml
model_path: training/models/lgbm_ranker.txt
feature_cols_base:
  - cooc_count
  - kiosk_product_cnt
  - pop_channel
  - pop_region
  - pop_store
  - channel_Mayorista
  - channel_Ruta
  - channel_Foodservice
  - channel_Distribuidores
  - channel_Supermercados
