extends: base_train.yaml
model_path: training/models/lgbm_ranker.txt
features_path: training/models/lgbm_features.txt
feature_cols_base:
  - cosine_sim
  - kiosk_product_cnt
  - pop_store
  - kiosk_bought_candidate_before
  - anchor_kiosk_frequency
  - cand_is_new_for_kiosk
  - channel_Mayorista
  - channel_Ruta
  - channel_Foodservice
  - channel_Distribuidores
  - channel_Supermercados
